### ISSUE TITLE
Update container setup for TravisCI

### ISSUE THREAD

**Issue by oubiwann** [clojusc/protobuf#34]
Sometime in the last week, Travis CI changed the default container setup we've been using for CI/CD on this project. Last week, everything built find; this morning, I'm seeing these errors on Travis:

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid, and setgid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
```

I've done this before, I just have to look at the Travis docs to get what we need.

**Comment by oubiwann** [comment]
Switch to use:
```
addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotoc-dev
```

Tests are running again.
